/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthCategoriesRouteImport } from './routes/_auth/categories'
import { Route as AuthBannersRouteImport } from './routes/_auth/banners'
import { Route as AuthProductsIndexRouteImport } from './routes/_auth/products/index'
import { Route as AuthOrdersIndexRouteImport } from './routes/_auth/orders/index'
import { Route as AuthProductsIdRouteImport } from './routes/_auth/products/$id'
import { Route as AuthOrdersIdRouteImport } from './routes/_auth/orders/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriesRoute = AuthCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBannersRoute = AuthBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsIndexRoute = AuthProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersIndexRoute = AuthOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsIdRoute = AuthProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersIdRoute = AuthOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/banners': typeof AuthBannersRoute
  '/categories': typeof AuthCategoriesRoute
  '/settings': typeof AuthSettingsRoute
  '/orders/$id': typeof AuthOrdersIdRoute
  '/products/$id': typeof AuthProductsIdRoute
  '/orders/': typeof AuthOrdersIndexRoute
  '/products/': typeof AuthProductsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/banners': typeof AuthBannersRoute
  '/categories': typeof AuthCategoriesRoute
  '/settings': typeof AuthSettingsRoute
  '/': typeof AuthIndexRoute
  '/orders/$id': typeof AuthOrdersIdRoute
  '/products/$id': typeof AuthProductsIdRoute
  '/orders': typeof AuthOrdersIndexRoute
  '/products': typeof AuthProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/banners': typeof AuthBannersRoute
  '/_auth/categories': typeof AuthCategoriesRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/orders/$id': typeof AuthOrdersIdRoute
  '/_auth/products/$id': typeof AuthProductsIdRoute
  '/_auth/orders/': typeof AuthOrdersIndexRoute
  '/_auth/products/': typeof AuthProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/banners'
    | '/categories'
    | '/settings'
    | '/orders/$id'
    | '/products/$id'
    | '/orders/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/banners'
    | '/categories'
    | '/settings'
    | '/'
    | '/orders/$id'
    | '/products/$id'
    | '/orders'
    | '/products'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/banners'
    | '/_auth/categories'
    | '/_auth/settings'
    | '/_auth/'
    | '/_auth/orders/$id'
    | '/_auth/products/$id'
    | '/_auth/orders/'
    | '/_auth/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories': {
      id: '/_auth/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthCategoriesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/banners': {
      id: '/_auth/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AuthBannersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/': {
      id: '/_auth/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthProductsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders/': {
      id: '/_auth/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthOrdersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/$id': {
      id: '/_auth/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthProductsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders/$id': {
      id: '/_auth/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthOrdersIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthBannersRoute: typeof AuthBannersRoute
  AuthCategoriesRoute: typeof AuthCategoriesRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthOrdersIdRoute: typeof AuthOrdersIdRoute
  AuthProductsIdRoute: typeof AuthProductsIdRoute
  AuthOrdersIndexRoute: typeof AuthOrdersIndexRoute
  AuthProductsIndexRoute: typeof AuthProductsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBannersRoute: AuthBannersRoute,
  AuthCategoriesRoute: AuthCategoriesRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthOrdersIdRoute: AuthOrdersIdRoute,
  AuthProductsIdRoute: AuthProductsIdRoute,
  AuthOrdersIndexRoute: AuthOrdersIndexRoute,
  AuthProductsIndexRoute: AuthProductsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
